---
storage:
  driver:
    kvp:
      key:
        length: 12
    control:
      scope: true
      kvt: true
      timeoutMillis: 5000
    family:
      key:
        enabled: false
        count: 0
        allow:
          empty: false
    multi:
      key:
        enabled: false
    scaling:
      partitions: 1
  namespace: goose
  net:
    bindBacklogSize: 0
    interestOpQueued: false
    keepAlive: true
    linger: 0
    maxConnPerSegmentstore: 10
    reuseAddr: true
    rcvBuf: 0
    sndBuf: 0
    tcpNoDelay: true
    timeoutMillis: 0
    ssl: false
    uri:
      schema: tcp
    node:
      addrs:
        - 127.0.0.1
      port: 9090
