---
storage:
  driver:
    kvp:
      key:
        length: int
    control:
      scope: boolean
      kvt: boolean
      timeoutMillis: long
    family:
      key:
        enabled: boolean
        count: long
        allow:
          empty: boolean
    multi:
      key:
        enabled: boolean
    scaling:
      partitions: int
  namespace: string
  net:
    bindBacklogSize: int
    interestOpQueued: boolean
    keepAlive: boolean
    linger: int
    maxConnPerSegmentstore: int
    reuseAddr: boolean
    rcvBuf: int
    sndBuf: int
    tcpNoDelay: boolean
    timeoutMillis: int
    ssl: boolean
    uri:
      schema: string
    node:
      addrs: list
      port: int
      conn:
        attemptsLimit: int
