FROM openjdk:8u181-jre-alpine

RUN apk add --update \
    rpcbind \
    nfs-utils \
    gcompat \
    python \
    jq \
    curl \
  && rm -rf /var/cache/apk/*

EXPOSE 9090 9091 10000 12345

WORKDIR /opt/pravega

COPY build/pravega_/ /opt/pravega/

ENTRYPOINT [ "/opt/pravega/bin/pravega-standalone" ]
